// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCycY9kDtw-ibRGpz_G3KJwP38f5KvCQ_s',
    appId: '1:778302661832:web:efa28bcbceac3b73c1b1fd',
    messagingSenderId: '778302661832',
    projectId: 'fasum-app-a5ad5',
    authDomain: 'fasum-app-a5ad5.firebaseapp.com',
    storageBucket: 'fasum-app-a5ad5.firebasestorage.app',
    measurementId: 'G-SN1HKKLPSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMSd4bkV9-Xes4-bvzhqEr9-MT1ee7UIM',
    appId: '1:778302661832:android:7d9f33d7edfb5c30c1b1fd',
    messagingSenderId: '778302661832',
    projectId: 'fasum-app-a5ad5',
    storageBucket: 'fasum-app-a5ad5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCycY9kDtw-ibRGpz_G3KJwP38f5KvCQ_s',
    appId: '1:778302661832:web:10bc339f08451d21c1b1fd',
    messagingSenderId: '778302661832',
    projectId: 'fasum-app-a5ad5',
    authDomain: 'fasum-app-a5ad5.firebaseapp.com',
    storageBucket: 'fasum-app-a5ad5.firebasestorage.app',
    measurementId: 'G-2E51K48T2Q',
  );
}
